name: Cache dependencies
on:
  push:
    branches:
      - master

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: List state of dependencies
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install
